### ISSUE TITLE
XSS & SQLi bypass + FPD

### ISSUE THREAD

**Issue by Souzus** [Alemalakra/xWAF#2]
Imagen 1 : ` https://image.prntscr.com/image/Mw8eB3GaQCuOj555zcYSYQ.png `
Envié la variable ` a ` con el valor ` ' ` y xWAF funciona porque ` a ` es un String.
Pero cuando se añade ` [] ` a la variable ` a `, dicha var. se convierte en array y xWAF genera varios FDP (Full Path Disclosure) y la protección deja de funcionar.
Imagen 2 : ` https://image.prntscr.com/image/TfKsUMYzQuOl_4mj4S3aXw.png `
Imagen 3 : ` https://image.prntscr.com/image/HdxfyFMdQQC0uBFgE97dOg.png `

**Comment by Alemalakra** [comment]
Reparado ahora, Gracias por reportar el bypass, Saludos de antemano.
