### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by rikkika** [Alemalakra/xWAF#4]
hello im using this waf on my forum but i have some bots spaming my site and im now using the: Sample Usage, but what is the best Advanced Usage settings for blocking bots / spam etc ??

**Comment by Alemalakra** [comment]
This is a web application firewall, Designed for vulnerabilitys, Not for block bots or either spam, I recommend you to speak with your web developer to install a captcha or a CSRF protection.

**Comment by mohsajeer** [comment]
can anyone please give me step by step usage ?
